version: 2

jobs:
  build:
    docker:
      - image: circleci/php:5.6
    working_directory: ~/spoof
    steps:
      - checkout
      - run:
          name: Update apt, install xdebug
          command: 'sudo apt-get update; sudo apt-get install -y php5-xdebug'
#      - run:
#          name: Set timezone to UTC
#          command: 'echo "date.timezone = UTC" > /opt/circleci/php/$(phpenv global)/etc/conf.d/date.ini'
      - run:
          name: Create test reports directory
          command: 'mkdir -p /phpunit'
      - run:
          name: Update composer
          command: 'composer self-update'
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run:
          name: Install composer dependencies
          command: 'composer install'
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run:
          name: Run Tests
          command: 'vendor/bin/phpunit -c src/tests/phpunit-log.xml'
      - run:
          name: Copy test results
          command: 'cp build/logs/junit.xml /phpunit/junit.xml'
      - store_test_results:
          path: /phpunit
      - store_artifacts:
          path: /phpunit
      - run:
          name: Report test results
          command: 'vendor/bin/test-reporter'
